"""The glue between the compiled vite frontend and our backend."""

from quart import Blueprint, current_app, send_from_directory

frontend_bp = Blueprint("frontend", __name__)


# Register frontend folder
# basically a reverse proxy for the frontend
_STATIC_FILES = (
    "assets",
    "logo_beets.png",
    "logo_flask.png",
    "favicon.ico",
    # PWA files generated by vite-plugin-pwa
    "sw.js",
    "manifest.webmanifest",
    "registerSW.js",
    "workbox-",
)


@frontend_bp.route("/", defaults={"path": "index.html"})
@frontend_bp.route("/<path:path>")
async def reverse_proxy(path):
    """Link to vite resources."""
    if not any(token in path for token in _STATIC_FILES):
        path = "index.html"
    elif "assets" in path:
        path = path[path.index("assets"):]

    r = await send_from_directory(current_app.config["FRONTEND_DIST_DIR"], path)
    return r
